Update bin/dev

diff --git a/bin/dev b/bin/dev
--- a/bin/dev
+++ b/bin/dev
@@ -1,10 +1,17 @@
 #!/usr/bin/env bash
 
-bin/link
-
-if [ -x "$(command -v overmind)" ]
-then
+# Check if the 'overmind' command is available
+if [ -x "$(command -v overmind)" ]; then
+  # If 'overmind' is available, start the development environment using it
   overmind start -f Procfile.dev "$@"
 else
-  foreman start -f Procfile.dev "$@"
+  # If 'overmind' is not available, check if 'foreman' is available
+  if [ -x "$(command -v foreman)" ]; then
+    # If 'foreman' is available, start the development environment using it
+    foreman start -f Procfile.dev "$@"
+  else
+    # If neither 'overmind' nor 'foreman' is available, display an error message
+    echo "Error: Neither 'overmind' nor 'foreman' is installed. Please install one of them."
+    exit 1
+  fi
 fi
